### ISSUE TITLE
Reference to $cookie not clear on 'Resume Playback w/ Cookies' Demo

### ISSUE THREAD

**Issue by waxidiotic** [jwplayer/jwdeveloper-demos#145]
I had a customer contact Support about the [Resume Playback w/ Cookies](https://developer.jwplayer.com/jw-player/demos/advanced/resume-playback-with-cookies/) demo saying that it wasn't working. When I looked at his code, he wasn't declaring `$cookies` or assigning anything to it.

Could we make it clearer by either including `var $cookies = whatever...` or advising people to check the source code of the page for it?

**Comment by madikarizma** [comment]
@josiekeller @monibons Easy to overlook because it's rate, but we should all make a note to check issues periodically.

@waxidiotic I'll see what I can do.

**Comment by josiekeller** [comment]
This was based on Cooper's suggestion to hide the cookie code, but we can certainly move it back in or at least put a comment in main.js telling them where to find it.

**Comment by waxidiotic** [comment]
@monibons i stumbled upon this in my github. i was so young back then...

anyway, i want to switch this demo out with one that uses local storage. thoughts?

**Comment by monibons** [comment]
If you want update that demo to use local storage, that sounds fine to me? I don't really have any strong opinions about this demo.

**Comment by waxidiotic** [comment]
cool, i'll close this issue
