### ISSUE TITLE
How can I use 360 video in mobile devices? 

### ISSUE THREAD

**Issue by klouskingsley** [jwplayer/jwdeveloper-demos#217]
How can I use 360 video in mobile devices? 
I am follwing the demo([link](https://github.com/jwplayer/jwdeveloper-demos/tree/master/demos/innovation/360-video)), it works on my laptop. 
But when I emulate mobile devices in my laptop chrome, the page shows 'Error loading player: No playable sources found' and there is no error in the console tab of dev-tools .

When I inspect devices in my mobile chrome on the mobile phone , the page shows 'Setup Timeout Error. Setup took longer than 30 seconds to complete.', there is an error 'provider.html5.js:1 Uncaught SyntaxError: Unexpected token <' in the console tab of dev-tools.

**Comment by klouskingsley** [comment]
Here is my code in the site: [ mudu.tv/show.php?a=test](http://mudu.tv/show.php?a=test)

**Comment by josiekeller** [comment]
The 360 demo is compatible with the latest Chrome, Firefox & Edge desktop browsers as well as Safari on iOS and in Chrome on Android. Please let us know if you're still having issues.
