### ISSUE TITLE
Does it works for multiple videos ?

### ISSUE THREAD

**Issue by cristiantimar** [jwplayer/jwdeveloper-demos#298]
Does the script works for multiple vidoes?

For example if I play 2 or more videos on same site and if I will come back, the cookie will remember all videos, or only the last video played ?

**Comment by josiekeller** [comment]
Hey Christian - are you referring to resuming playback with cookies? https://developer.jwplayer.com/jw-player/demos/advanced/resume-playback-with-cookies/

**Comment by cristiantimar** [comment]
Hello Josie. Yes about resuming playback with cookies.

**Comment by monibons** [comment]
Hi Christian,

You should be able to achieve this with multiple players by using a for loop to run through the cookie function for each instance of a player on your page.

**Comment by cristiantimar** [comment]
I see. It is efficient only if I use few videos.
But if I have more than 20.000 videos, the loop is not efficient.

**Comment by cristiantimar** [comment]
By the way thanks for sugestions.
I will create a cookie for every videos which will expire after few days.
